CosmeticShop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('cart/', include('cart.urls')),
    path('', include('shop.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from accounts import views

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    path('register/', views.register, name='register'),
]

cart/urls.py
from django.urls import path

from cart import views

app_name = 'cart'

urlpatterns = [
    path('',views.detail, name='detail'),
    path('add/<int:product_id>/',views.add, name='product_add'),
    path('remove/<int:product_id>/',views.remove, name='product_remove'),
]

shop/urls.py
from django.urls import path

from shop import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_in_category, name='product_all'),
    path('<slug:category_slug>/', views.product_in_category, name='product_in_category'),
    path('<int:id>/<product_slug>/', views.product_detail, name='product_detail'),
]

cart/models.py
from django.db import models

# Create your models here.

shop/models.py
from django.db import models
from django.shortcuts import resolve_url


class Category(models.Model) :
    # 속성 아이메이크업 베이스메이크업 립메이크업
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, allow_unicode=True, unique=True) #url에 내 카테고리 이름이 보이게.. 아이디처럼 움직임 겹치면 안됨. => UNIQUE

    # class Meta
    class Meta :
        ordering = ['name']
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    # __str__
    def __str__(self):
        return self.name

    # get_absolute_url()
    def get_absolute_url(self):
        return resolve_url('shop:product_in_category', self.slug)
    

class Product(models.Model):
    # name
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, allow_unicode=True, unique=True)
    # price
    price = models.DecimalField(max_digits=10, decimal_places=2) #100원 $9.99
    # category
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, related_name='products')
    # image
    image = models.ImageField(upload_to='products/%y/%m/%d', default='products/no_image.jpg')
    # stock
    stock = models.PositiveIntegerField()
    # description 설명
    description = models.TextField(blank=True)

    available_display = models.BooleanField('Display', default=True)
    available_order = models.BooleanField('Order', default=True)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return resolve_url('shop:product_detail', self.id, self.slug)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User


class RegisterForm(forms.ModelForm):
    password = forms.CharField(label='패스워드', widget=forms.PasswordInput)
    password2 = forms.CharField(label='패스워드 확인', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('패스워드가 같아야합니다.')

        return cd['password2']

cart/forms.py
from django import forms


class AddProductForm(forms.Form):
    quantity = forms.IntegerField()
    is_update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

accounts/views.py
from django.shortcuts import render

from accounts.forms import RegisterForm


def register(request):
    if request.method == 'POST' :
        #회원가입 데이터 입력하고 버튼 눌렀을 때
        user_form = RegisterForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
        return render(request, 'accounts/register_done.html', {'new_user' : new_user})
    else : #회원가입폼 나오게
        user_form = RegisterForm()

    return render(request, 'accounts/register.html', {'form' : user_form})

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST

from cart.cart import Cart
from cart.forms import AddProductForm
from shop.models import Product


@require_POST
def add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)

    form = AddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], is_update=cd['is_update'])

    return redirect('cart:detail')


def remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)

    return redirect('cart:detail')

def detail(request):
    cart = Cart(request)
    for product in cart:
        product['quantity_form'] = AddProductForm(initial={'quantity': product['quantity'], 'is_update':True})
    return render(request, 'cart/detail.html',{'cart':cart})

shop/views.py
from django.shortcuts import render, get_object_or_404

from cart.forms import AddProductForm
from shop.models import Category, Product


def product_in_category(request, category_slug=None):
    current_category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available_display=True)

    if category_slug:
        current_category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=current_category)

    return render(request, 'shop/list.html', {'categories': categories, 'products': products})


def product_detail(request, id, product_slug):
    product = get_object_or_404(Product, id=id, slug=product_slug)
    add_to_cart = AddProductForm(initial={'quantity': 1})
    return render(request, 'shop/detail.html', {'product': product, 'add_to_cart': add_to_cart})

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %} 코스메틱 로그인{% endblock %}

{% block content %}
    로그인 정보를 입력하세요.
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="코스메틱 로그인">
    </form>
{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'base.html' %}

{% block title %} 코스메틱 로그아웃{% endblock %}

{% block content %}
    성공적으로 로그아웃 되었습니다.
    <a href="{% url 'login' %}">다시 로그인</a>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block title %} 회원가입{% endblock %}

{% block content %}
    회원 정보를 입력하세요.
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="회원가입">
    </form>
{% endblock %}

accounts/templates/accounts/retgister_done.html
{% extends 'base.html' %}

{% block title %} 회원가입 성공{% endblock %}

{% block content %}
회원등록 되었습니다.
    {{ new_user.username }}님 환영합니다.
    <a href="{% url 'shop:product_all' %}">쇼핑하러가기</a>
{% endblock %}

cart/templates/cart/detail.html
{% extends 'base.html' %}

{% block title %}Shopping Cart{% endblock %}

{% block content %}
    <table>
        <thead>
        <tr>
            <th>Image</th>
            <th>Product</th>
            <th>Quantity</th>
            <th>Remove</th>
            <th>Unit price</th>
            <th>Price</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
                <tr>
                    <td><a href="{{ product.get_absolute_url }}"><img src="{{ product.image.url }}" width="100" alt=""></a></td>
                    <td>{{ product.name }}</td>
                    <td>
                        <form action="{% url 'cart:product_add' product.id %}" method="post">
                            {% csrf_token %}
                            {{ item.quantity_form.quantity }}
                            {{ item.quantity_form.is_update }}
                            <input type="submit" value="Update">
                        </form>
                    </td>
                    <td><a href="{% url 'cart:product_remove' product.id %}">Remove</a></td>
                    <td>${{ item.price }}</td>
                    <td>${{ item.total_price }}</td>
                </tr>
            {% endwith %}
        {% endfor %}
        <tr>
            <td>Total</td>
            <td colspan="4"></td>
            <td>${{ cart.get_product_total|floatformat:"2" }}</td>
        </tr>
        </tbody>
    </table>
    <p>
        <a href="{% url 'shop:product_all' %}">계속 쇼핑하기</a>
    </p>
{% endblock %}

shop/templates/shop/detail.html
{% extends 'base.html'%}

{% block title %} Product Detail{% endblock %}

{% block content %}
    <img src="{{ product.image.url }}" width="100" alt="">
    <h1>{{ product.name }}</h1>
    <p>Price: ${{ product.price }}</p>
    <p>Description: {{ product.description|linebreaks }}</p>
    <p>
    <form action="{% url 'cart:product_add' product.id %}" method="post">
        {% csrf_token %}
        {{ add_to_cart }}
        <input type="submit" value="장바구니에 추가">
    </form>
    </p>
{% endblock %}

shop/templates/shop/list.html
{% extends 'base.html' %}

{% block title %} List{% endblock %}

{% block content %}
<a href="{% url 'shop:product_all' %}">ALL</a>
{% for category in categories %}
    <a href="{{ category.get_absolute_url }}">{{ category }}</a>
{% endfor %}
<p></p>
{% for product in products %}
    <img src="{{ product.image.url }}" width="100" height="100" alt="">
    <h3>{{ product.name }}</h3>
    <p>{{ product.description }}</p>
    <p>{{ product.price }}</p>
    <a href="{{ product.get_absolute_url }}">View Detail</a><br>
    <p></p>
{% endfor %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>DGoodsShop{% block title %}{% endblock %}</title>
</head>
<body>

{% if user.is_authenticated %}
<a href="{% url 'logout' %}">Logout</a>
{% else %}
<a href="{% url 'login' %}">Login</a>
    <a href="{% url 'register' %}">회원가입</a>
{% endif %}
<a href="{% url 'cart:detail' %}">Cart
    {% if cart|length > 0 %}
        ${{ cart.get_product_total }} with {{ cart|length }} items
    {% else %}
        : Empty
    {% endif %}
</a>
<p></p>

{% block content %}

{% endblock %}
</body>
</html>